convirza:
  group:
    agency: {group_id: 25056, group_ext_id: 123abcdefghi, group_name: QA automation,
      group_parent_id: 0, top_group_id: 25053, billing_id: 25053, address: pune-lake
        town, city: Salt Lake City, state: UT, zip: '10006', phone_number: (801) 878-6943,
      industry_id: 1}
    company: {group_id: 51306, group_ext_id: l5o3mak6yjraxov8sdmd, group_name: API
        Company Group, group_parent_id: 25053, top_group_id: 25053, billing_id: 25053,
      address: Pune, city: Salt Lake City, state: UT, zip: '10006', phone_number: '8646983532',
      industry_id: 1}
    location: {group_id: 51309, group_ext_id: ds4djrwo477rbyjjdtdu, group_name: API
        Location Group, group_parent_id: 51306, top_group_id: 25053, billing_id: 25053,
      address: Pune, city: Salt Lake City, state: UT, zip: '10006', phone_number: '5233745207',
      industry_id: 1}
  user:
    agency: {id: 11622, user_ext_id: '', first_name: QA, last_name: Automation, email: qaautomation@yopmail.com,
      phone_number: '', role: Admin, status: Active, group_id: 25053}
    company: {id: '15723', user_ext_id: gg94rv0x0ivbc2cc353f, first_name: Company,
      last_name: Admin, email: convirza_user666204@yopmail.com, phone_number: null,
      role: Admin, status: Active, group_id: null}
    location: {id: '15696', user_ext_id: fcjsl14ue66shzq9r35w, first_name: Location,
      last_name: Admin, email: convirza_user288509@yopmail.com, phone_number: null,
      role: Admin, status: Active, group_id: null}
  campaign:
    agency:
      campaign_id: null
      campaign_name: Agency Campaign API
      campaign_ext_id: 15707a6d-5af1-4c1b-b5e9-6d582e08087d
      campaign_created: '2021-05-27T16:30:03.602Z'
      campaign_status: active
      group_id: 25053
      campaign_modified: '2021-05-27T16:30:03.602Z'
      campaign_start_date: '2021-05-27T16:30:03.602Z'
      campaign_end_date: '2021-06-11T16:30:03.604Z'
      campaign_owner_user_id: 11622
      campaign_users: [11622]
    company:
      campaign_id: null
      campaign_name: Company Campaign API
      campaign_ext_id: acf701b9-e402-459b-8f8b-c7f8ed9c5202
      campaign_created: '2021-05-27T16:30:09.945Z'
      campaign_status: active
      group_id: 51275
      campaign_modified: '2021-05-27T16:30:09.945Z'
      campaign_start_date: '2021-05-27T16:30:09.945Z'
      campaign_end_date: '2021-06-11T16:30:09.945Z'
      campaign_owner_user_id: 15695
      campaign_users: [15695]
    location:
      campaign_id: null
      campaign_name: Location Campaign API
      campaign_ext_id: 33454b0c-40c3-4739-9830-4179e42e818f
      campaign_created: '2021-05-27T16:30:16.017Z'
      campaign_status: active
      group_id: 51276
      campaign_modified: '2021-05-27T16:30:16.017Z'
      campaign_start_date: '2021-05-27T16:30:16.017Z'
      campaign_end_date: '2021-06-11T16:30:16.018Z'
      campaign_owner_user_id: 15696
      campaign_users: [15696]
  callflow:
    agency:
      call_flow_id: null
      call_flow_name: Agency Callflow API
      call_flow_created: null
      call_flow_status: active
      repeat_interval: 72
      call_value: 0
      channel_id: 7
      message_enabled: true
      message: Agency Callflow Message
      default_ringto: '8018786943'
      group_id: 25053
      email_to_notify: null
      play_disclaimer: null
      created_at: null
      updated_at: '2021-05-27T16:30:24.327Z'
      voicemail_enabled: false
      routable_type: SimpleRoute
      webhook_enabled: false
      record_until: '2021-06-11T16:30:24.328Z'
      whisper_enabled: true
      whisper_message: Agency Whisper Message
      ring_delay: null
      postcall_ivr_enabled: false
      postcall_ivr_id: 0
      spam_threshold: 0
      spam_filter_enabled: false
      referral_number: null
      campaign_id: 49997
      number: {phone_number_id: 977347, phone_number: 8666234179}
    company:
      call_flow_id: null
      call_flow_name: Company Callflow API
      call_flow_created: null
      call_flow_status: active
      repeat_interval: 72
      call_value: 0
      channel_id: 7
      message_enabled: true
      message: Company Callflow Message
      default_ringto: '8018786943'
      group_id: 51275
      email_to_notify: null
      play_disclaimer: null
      created_at: null
      updated_at: '2021-05-27T16:30:29.051Z'
      voicemail_enabled: false
      routable_type: SimpleRoute
      webhook_enabled: false
      record_until: '2021-06-11T16:30:29.051Z'
      whisper_enabled: true
      whisper_message: Company Whisper Message
      ring_delay: null
      postcall_ivr_enabled: false
      postcall_ivr_id: 0
      spam_threshold: 0
      spam_filter_enabled: false
      referral_number: null
      campaign_id: 49998
      number: {phone_number_id: 901961, phone_number: 8559568339}
    location:
      call_flow_id: null
      call_flow_name: Location Callflow API
      call_flow_created: null
      call_flow_status: active
      repeat_interval: 72
      call_value: 0
      channel_id: 7
      message_enabled: true
      message: Location Callflow Message
      default_ringto: '8018786943'
      group_id: 51276
      email_to_notify: null
      play_disclaimer: null
      created_at: null
      updated_at: '2021-05-27T16:30:33.230Z'
      voicemail_enabled: false
      routable_type: SimpleRoute
      webhook_enabled: false
      record_until: '2021-06-11T16:30:33.230Z'
      whisper_enabled: true
      whisper_message: Location Whisper Message
      ring_delay: null
      postcall_ivr_enabled: false
      postcall_ivr_id: 0
      spam_threshold: 0
      spam_filter_enabled: false
      referral_number: null
      campaign_id: 49999
      number: {phone_number_id: 954156, phone_number: 4022605989}
  webhook:
    agency: {webhook_id: null, webhook_status: active, org_unit_id: 25053, webhook_Name: Agency
        Webhook API, description: Webhook Created on Agency Group, webhook_Endpoint: 'https://encfelub0xc55.x.pipedream.net/',
      method: POST, format: XML, include_DNI_Logs: true, include_Indicator_Scores: true}
    company: {webhook_id: null, webhook_status: active, org_unit_id: 50944, webhook_Name: Company
        Webhook API, description: Webhook Created on Company Group, webhook_Endpoint: 'https://enqoyq9u0u6p8.x.pipedream.net/',
      method: POST, format: JSON, include_DNI_Logs: true, include_Indicator_Scores: true}
    location: {webhook_id: null, webhook_status: active, org_unit_id: 50945, webhook_Name: Location
        Webhook API, description: Webhook Created on Location Group, webhook_Endpoint: 'https://eni32vd61fhji.x.pipedream.net/',
      method: POST, format: XML, include_DNI_Logs: true, include_Indicator_Scores: true}
  custom_source:
    agency: {org_unit_id: 25053, custom_source_id: 6181, custom_source_name: Agency
        Custom Source}
    company: {org_unit_id: 51275, custom_source_id: 5924, custom_source_name: Company
        Custom Source}
    location: {org_unit_id: 51276, custom_source_id: 5925, custom_source_name: Location
        Custom Source}
  blacklisted_number:
    agency: {number: '1234567891'}
